version: 2
jobs:
  build:
    docker:
      - image: kauplan/review2.5
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: create pdf
          command: |
            ln -f config.prod.yml config.yml
            export STARTER_TARGET=ebook; 
            rake pdf
      - run: ls -l cognito-userpool-in-action.pdf
      - store_artifacts:
          path: ~/work/cognito-userpool-in-action.pdf
          destination: pdf
      - persist_to_workspace:
          root: ~/work
          paths:
            - cognito-userpool-in-action.pdf
  deploy:
    docker:
      - image: justincasetech/aws-cli:1.16.186-jq1.6-git
    working_directory: ~/work
    steps:
      - attach_workspace:
          at: ~/work
      - run: aws s3 cp cognito-userpool-in-action.pdf s3://hiroga-techbookfest/d2f64fa7-09cc-4570-b05d-dddd33248aa2 --acl public-read

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
            tags:
              only: /deploy/
      - deploy:
          context: hiroga-aws
          filters:
            branches:
              only: master
            tags:
              only: /deploy/
          requires:
            - build
