version: 2
jobs:
  build:
    docker:
      - image: kauplan/review2.5
    working_directory: ~/work
    steps:
      - checkout
      - run: rake pdf
      - run: ls -l cognito_user_migration.pdf
      - store_artifacts:
          path: ~/work/cognito_user_migration.pdf
          destination: pdf
      - persist_to_workspace:
          root: ~/work
          paths:
            - cognito_user_migration.pdf
  deploy:
    docker:
      - image: justincasetech/aws-cli:1.16.186-jq1.6-git
    working_directory: ~/work
    steps:
      - attach_workspace:
          at: ~/work
      - run: ./publish_pdf_to_s3.sh

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
            tags:
              only: /deploy/
      - deploy:
          context: hiroga-aws
          filters:
            branches:
              only: master
            tags:
              only: /deploy/
          requires:
            - build
