version: 2
jobs:
  build:
    docker:
      - image: kauplan/review2.5
    working_directory: ~/work
    steps:
      - checkout
      - run: rake pdf
      - run: ls -l cognito_user_migration.pdf
      - store_artifacts:
          path: ~/work/cognito_user_migration.pdf
          destination: pdf

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: hiroga-aws
          filters:
            branches:
              only: master
            tags:
              only: /deploy/
