version: 2
jobs:
  build:
    docker:
      - image: kauplan/review2.5
    working_directory: ~/work
    steps:
      - checkout
      - run: 
          name: create pdf
          command: |
            ln -f config.prod.yml config.yml
            rake pdf
      - run: ls -l cognito_userpool_in_action.pdf
      - store_artifacts:
          path: ~/work/cognito_userpool_in_action.pdf
          destination: pdf
      - persist_to_workspace:
          root: ~/work
          paths:
            - cognito_userpool_in_action.pdf
  deploy:
    docker:
      - image: justincasetech/aws-cli:1.16.186-jq1.6-git
    working_directory: ~/work
    steps:
      - attach_workspace:
          at: ~/work
      - run: aws s3 cp cognito_userpool_in_action.pdf s3://hiroga-cognito-user-migration/cognito_userpool_in_action.pdf --acl public-read

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
            tags:
              only: /deploy/
      - deploy:
          context: hiroga-aws
          filters:
            branches:
              only: master
            tags:
              only: /deploy/
          requires:
            - build
